OnShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('chat/', include('chat.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

chat/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('<str:room_name>/', views.room, name='room'),
    path('', lambda request: redirect('/chat/default/')),  # Redirect /chat/ to a default room
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

chat/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'{self.name} added'

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id =product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

chat/views.py
from django.shortcuts import render

def room(request, room_name):
    return render(request, 'chat/room.html', {'room_name': room_name})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.http import HttpResponse

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                    'categories': categories,
                   'products': products,
                   })

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})


def index(request):
    title = {'greeting': 'Welcome to the shop!'}
    return render(request,
                  'shop/index.html', title)

cart/templates/cart/detail.html
{% extends "shop/main.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
{% if not cart %}
<p>Your cart is empty.</p>
{% else %}
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img
                        src="{% if product.image %}{{ product.image.url }}{% else %}{% static  'img/no_pictures.png' %}{% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>
                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Remove</button>
                </form>
            </td>
            <td class="num">${{ item.price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url  'shop:product_list' %}" class="button
light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>
</p>
{% endif %}
{% endblock %}

chat/templates/chat/room.html
<!DOCTYPE html>
<html>

<head>
    <title>Chat Room</title>
</head>

<body>
    <h1>Chat Room</h1>
    <div id="chat-log"></div>
    <input id="chat-message-input" type="text" size="100">
    <button id="chat-message-submit">Send</button>

    <script>
        const roomName = "{{ room_name }}";
        const chatSocket = new WebSocket(
            'ws://' + window.location.host + '/ws/chat/' + roomName + '/');

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').innerHTML += (data.message + '<br>');
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // Enter key
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>

</html>

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My shop {% endblock %}</title>
</head>

<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            <a href="{% url 'cart:cart_detail' %}">My cart</a>
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
            Your cart:
            <a href="{% url 'cart:cart_detail' %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
            </a>
            {% else %}
            Your cart is empty.
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

shop/templates/shop/index.html
{% extends "shop/main.html" %}

{% block content %}
<section class="hero">
    <div class="hero-container">
        <h2>Campus Marketplace For Accommodations And More</h2>
        <p>Search accommodations, buy, sell your new or used properties and connect with ease the student way
        </p>
        <div class="cta-buttons">
            <button class="btn primary">List Your Property</button>
            <button class="btn secondary">Explore Now</button>
        </div>
    </div>
</section>

{% endblock %}

shop/templates/shop/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Campus Marketplace</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
    <header class="header">
        <div class="container">
            <div class="logo">
                <img src="{% static 'img/swivly.png' %}" alt="Swivly Logo">
                <h1>Swivly</h1>
            </div>
            <nav class="nav">
                <a href="{% url 'shop:index' %}">Home</a>
                <a href="{% url 'shop:product_list' %}">Market Place</a>
                <a href="#">Accommodation</a>
                <a href="#">Contact Us</a>
                <div class="auth">
                    <button class="btn login">Log In</button>
                    <button class="btn signup">Sign Up</button>
                </div>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}


        {% endblock %}
    </main>
</body>

</html>

shop/templates/shop/product/detail.html
{% extends "shop/main.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_pictures.png' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
        </a>
    </h2>
    <p class="price">${{ product.price }}</p>
    {{ product.description|linebreaks }}
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Add to Cart</button>
    </form>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/main.html" %}
{% load static %}
{% block title %}
{% if category and category.name %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if c.is_selected %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>


        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% if products %}
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img
                src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-pictures.png' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        ${{ product.price }}
    </div>
    {% endfor %}
    {% else %}
    <p>No products available in this category.</p>
    {% endif %}
</div>
{% endblock %}